
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion/bin/cmake/linux/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.12.21-4-MANJARO - x86_64
...
